apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: 804867352391.dkr.ecr.us-east-1.amazonaws.com/dev/frontend:latest
          ports:
          - containerPort: 5713
      imagePullSecrets:
      - name: myregistrykey
          