services:
  backend:
    container_name: backend
    # build: #used for local devlopement
    #   context: backend/
    # image: backend-image

    image: ${ECR_BACKEND_IMAGE_URI}
    ports:
      - "8500:8500"
    environment:
      MONGODB_URL: ${MONGODB_URL}
  
  frontend:
    container_name: frontend
    # build: #used for local devlopement
    #   context: frontend/
    # image: frontend-image

    image: ${ECR_FRONTEND_IMAGE_URI}
    ports:
      - "5173:80"
    depends_on:
      - backend