services:
  database:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    ports:
     - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    container_name: backend
    # build: #used for local devlopement
    #   context: backend/
    # image: backend-image

    image: ${ECR_BACKEND_IMAGE_URI}
    ports:
      - "8500:8500"
    environment:
      MONGODB_URL: mongodb://database:27017/todo
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    container_name: frontend
    # build: #used for local devlopement
    #   context: frontend/
    # image: frontend-image

    image: ${ECR_FRONTEND_IMAGE_URI}
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network
  
volumes:
  mongo-data:

networks:
  app-network:
